---
title: "Enviromental Justice"
author: "Elinai Alicia Severiano Perez"
format:
  html:
    toc: true
    toc-depth: 2
    embed-resources: true
---

# Preparing Data
```{r}
# Loading Packages
library(dplyr)
library(ggplot2)
library(tidyverse)
library(sf)
library(tigris)
library(leaflet)
library(tidycensus)
```

## Load Data
```{r,message=FALSE, warning=FALSE}
# Power Plant Data
Power_Plants <- read_csv("Power_Plants.csv")  %>%
   filter(State == "Minnesota") %>%
  mutate(fossil_fuel = ifelse(PrimSource %in% c("coal", "petroleum", "natural gas"), "Fossil Fuel", "Renewable"))

# Environmental justice areas (subseted)
ej_spaces <- read_csv("csv_env_ej_mpca_census/ej_mpca_census.csv") %>%
  select(-Shape_Area, -Shape_Length, -source, -statefp, -funcstat, -name, 
         -namelsad, -mtfcc, -intptlat, -intptlon, -geography, -countyfp, 
         -aland, -awater)
```

```{r, message=FALSE, warning=FALSE}
# Loading more data for census tracts
mn_tracts <- tracts(state = "MN", cb = TRUE, year = 2023) %>%
  st_transform(crs = 4326)%>%
  mutate(GEOID = as.double(GEOID),
         County = gsub(" County", "", NAMELSADCO))  %>%
  select(GEOID, geometry, County) 
  
# Join Environmental Justice Data
ej_tracts <- mn_tracts %>%
  left_join(ej_spaces, by = c("GEOID" = "geoid"))

```


## Initial Wrangling
```{r}
# Subseting to find each type of case of enviromental justice areas

# 40% or more of estimate population with limited English proficiency, based on maxprplep (calculated) &
# Max estimated population that identify as people of color is 50% or more, based on maxprppoc (calculated)	&
# 35% or more of estimate population under 200% of the federal poverty level, based on prp200x (calculated)
statuselp_filtered <- ej_spaces %>%
  filter(statuslep == "YES") %>%
  left_join(mn_tracts, by = c("geoid" = "GEOID")) %>%
  mutate(EJ_area = "ALL")

# ONLY 35% or more of estimate population under 200% of the federal poverty level, based on prp200x (calculated)
status200x_filtered <- ej_spaces %>%
  filter(status200x == "YES" & statuspoc == "NO" & statuslep == "NO")%>%
  left_join(mn_tracts, by = c("geoid" = "GEOID")) %>%
  mutate(EJ_area = "ONLY LOW INCOME")

# ONLY Max estimated population that identify as people of color is 50% or more, based on maxprppoc (calculated)	&
statuspoc_filtered <- ej_spaces %>%
  filter(statuspoc == "YES" & status200x == "NO"  & statuslep == "NO")%>%
  left_join(mn_tracts, by = c("geoid" = "GEOID"))  %>%
  mutate(EJ_area = "ONLY POC")

# BOTH  Max estimated population that identify as people of color is 50% or more, based on maxprppoc (calculated)	&
# 35% or more of estimate population under 200% of the federal poverty level, based on prp200x (calculated)
low_income_poc_areas <- ej_spaces %>%
  filter(statuspoc == "YES" & status200x == "YES" & statuslep == "NO") %>%
  left_join(mn_tracts, by = c("geoid" = "GEOID")) %>%
  mutate(EJ_area = "ONLY POC & LOW INCOME")

# bring it all together
EJ_stacked <- bind_rows(statuselp_filtered, status200x_filtered,
                        statuspoc_filtered, low_income_poc_areas) %>%
  mutate(EJ_OR_NOT = TRUE)
```

## Random Wrangling
```{r}
# Subset fossil fuel power plants
fossil_power_plants <- Power_Plants %>%
  filter(fossil_fuel == "Fossil Fuel", County %in% EJ_stacked$County)

# Subset Reneable power plants
Renewable_power_plants <- Power_Plants %>%
  filter(fossil_fuel == "Renewable", County %in% EJ_stacked$County)

# transform to sf
ej_sf <- st_as_sf(EJ_stacked)
```

# Findings
##Initial Maps
```{r}
# colors for maps
   pal1 <- colorFactor(
      palette = c("#dc0073","#22577a", "#c44900", "#f4e285"),
      domain = c( "ALL", "ONLY LOW INCOME", "ONLY POC", "ONLY POC & LOW INCOME"))
```

```{r}
# Plot Fossil Fuel 
leaflet() %>%
  addPolygons(data = mn_tracts,
    color = "black",
    fillOpacity = 0,
    weight = 0.5) %>%
  addPolygons(
    data = ej_sf,
    fillColor = ~pal1(EJ_area), 
    fillOpacity = 0.7, 
    color = "white", 
    weight = 0.15
  ) %>%
  addLegend(
    pal = pal1, values = ej_sf$EJ_area, title ="Enviromental Justice Area")  %>%
  addCircleMarkers(
    data = fossil_power_plants,
    lng = ~Longitude,
    lat = ~Latitude,
    radius = 1.75,         
    fillOpacity = 0.75,  
    opacity = 0.1,      
    color = "#000000")  
```

```{r}
# Plot Fossil Fuel 
leaflet() %>%
  addPolygons(data = mn_tracts,
    color = "black",
    fillOpacity = 0,
    weight = 0.5) %>%
  addPolygons(
    data = ej_sf,
    fillColor = ~pal1(EJ_area), 
    fillOpacity = 0.7, 
    color = "white", 
    weight = 0.15
  ) %>%
  addLegend(
    pal = pal1, values = ej_sf$EJ_area, title ="Enviromental Justice Area")  %>%
  addCircleMarkers(
    data = Renewable_power_plants,
    lng = ~Longitude,
    lat = ~Latitude,
    radius = 1.75,         
    fillOpacity = 0.75,  
    opacity = 0.1,      
    color = "#000000")  
```

# Getting tract info per powerplant 
```{r}
# Loading in census data
mn_tracts <- tracts(state = "MN", year = 2020, class = "sf")
Power_Plants_sf <- st_as_sf(Power_Plants, coords = c("Longitude", "Latitude"), crs = 4326)

mn_tracts <- st_transform(mn_tracts, crs = st_crs(Power_Plants_sf))

# Bringing it together
Power_Plants_with_tract <- st_join(Power_Plants_sf, mn_tracts[, c("GEOID", "NAME", "COUNTYFP")], join = st_within)

```

```{r}
# Add a column to identify is power plant is part of EJ or Not also simplify df
plants_in_ej <- st_join(Power_Plants_with_tract, ej_sf, join = st_within) %>%
  mutate(EJ_OR_NOT = if_else(is.na(EJ_OR_NOT), FALSE, EJ_OR_NOT)) %>%
  select(X, Y, OBJECTID.x, Plant_Code, Plant_Name, County.x, Zip, PrimSource, 
         fossil_fuel, geometry, GEOID, NAME, COUNTYFP,EJ_OR_NOT, EJ_area)

# Find the count of power plants per census tracts
plants_in_ej_counts <- plants_in_ej %>%
  group_by(GEOID, fossil_fuel, EJ_OR_NOT) %>%
  summarize(plant_count = n())  
```

## Counts of power plants per census tracts

```{r}
plants_in_ej_counts %>%
  ggplot(aes(x = plant_count)) +
  geom_histogram(binwidth = 1, fill = "#c44900", color = "white") +
  theme_classic() +
  facet_wrap(~fossil_fuel + EJ_OR_NOT) +
  labs(title = "Distribution of Power Plants per Census Tract",
       subtitle = "Comparison by energy type and Environmental Justice area status",
       x = "Number of Power Plants per Census Tract", y = "Number of Census Tracts")

plants_in_ej_counts %>%
  filter(EJ_OR_NOT == TRUE) %>%
  ggplot(aes(x = plant_count)) +
  geom_histogram(binwidth = 1, fill = "#22577a", color = "white") +
  theme_classic() +
  facet_wrap(~fossil_fuel) +
  labs(title = "Distribution of Power Plants per Census Tract",
       subtitle = "Comparison by energy type for Enviromental Justice Areas",
       x = "Number of Power Plants per Census Tract", y = "Number of Census Tracts")

```

## Populations to where power plants are at
```{r}
# Getting population data
total_pop <- get_acs(geography = "tract", variables = "B01003_001", state = "MN", year = 2023, geometry = FALSE)

# Joining power plant + ej areas with population data
Power_Plants_with_pop <- plants_in_ej %>%
  left_join(total_pop %>% select(GEOID, estimate), by = "GEOID") %>%
  rename(total_population = estimate)


# power plant and population 
plants_per_pop <- Power_Plants_with_pop %>%
  group_by(GEOID, fossil_fuel, EJ_OR_NOT) %>%
  summarize(plant_count = n(), total_population = first(total_population), 
            plants_per_10k = (plant_count / total_population) * 10000)

# Plot all
plants_per_pop %>%
  ggplot(aes(x = plants_per_10k)) +
  geom_histogram( fill = "#c44900", color = "white") +
  theme_classic() +
  facet_wrap(~fossil_fuel + EJ_OR_NOT) +
 labs(title = "Distribution of Power Plants per 10,000 People",
      subtitle = "For type of power plants and environmental justice designation",
      x = "Power Plants per 10,000 Resident in Census Tract", y = "Count of Census Tracts")

# Plot on EJ
plants_per_pop %>%
  filter(EJ_OR_NOT == TRUE) %>%
  ggplot(aes(x = plants_per_10k)) +
  geom_histogram( fill = "#22577a", color = "white") +
  theme_classic() +
  facet_wrap(~fossil_fuel) +
   labs(title = "Distribution of Power Plants per 10,000 People",
      subtitle = "For each type of power plants in enviromental Justice Areas",
      x = "Power Plants per 10,000 Resident in Census Tract", y = "Count of Census Tracts")

```

# Proportion of tracts with power plants
```{r}
# tracts with ej info
mn_tracts_with_ej <- mn_tracts %>%
  select(GEOID, geometry) %>%
  mutate( GEOID = as.double(GEOID)) %>%
  left_join(EJ_stacked, by = c("GEOID" = "geoid")) %>%
   mutate(EJ_OR_NOT = if_else(is.na(EJ_OR_NOT), FALSE, EJ_OR_NOT)) 

# Making sure both geoid are char
Power_Plants_with_tract <- Power_Plants_with_tract %>%
  mutate(tractce = as.character(GEOID)) %>%
  select(X, Y, OBJECTID, Plant_Code, Plant_Name, County, Zip, PrimSource, 
         fossil_fuel, geometry, GEOID, NAME, COUNTYFP,)

mn_tracts_with_ej <- mn_tracts_with_ej %>%
  mutate(GEOID = as.character(GEOID))

mn_tracts_ej_pp <- mn_tracts_with_ej %>%
  left_join(Power_Plants_with_tract %>% st_drop_geometry(), by = "GEOID") %>%
  mutate(PowerPlant_orNot = if_else(is.na(Plant_Name), FALSE, TRUE)) 
```

```{r}
prop_tracts_pp <- mn_tracts_ej_pp %>%
  group_by(PowerPlant_orNot, EJ_OR_NOT) %>%
  summarize(tract_count = n())
```

```{r}
prop_tracts_pp_df <- as.data.frame(prop_tracts_pp) %>% select(-geometry.x) %>%
  rename(`Tracts with Power Plants` = PowerPlant_orNot,
         `Environmental Justice Area` = EJ_OR_NOT,
         `Count of Tracts` = tract_count)

prop_tracts_pp_df
```

```{r}
MI_Power_Plants <- read_csv("Power_Plants.csv")  %>%
   filter(State == "Michigan") %>%
  mutate(fossil_fuel = ifelse(PrimSource %in% c("coal", "petroleum", "natural gas"), "Fossil Fuel", "Renewable"))
```


```{r}
leaflet() %>%
  addCircleMarkers(
    data = MI_Power_Plants,
    lng = ~Longitude,
    lat = ~Latitude,
    radius = 1.75,         
    fillOpacity = 0.75,  
    opacity = 0.1,      
    color = "green")  
```

